/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Cetak;
import controller.DBI;
import controller.Matrix;
import controller.OlahData;
import controller.Praproses;
import controller.SOM;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
//    private int kodeData;
    private String nilai[][] = null;
    private String nilai2[][] = null;
    private String nilai3[][] = null;
    private double nilai4[][] = null;
    private double nilairandom[][] = null;
    private DefaultTableModel modelData, modelRandom, modelHasilCluster;
    long startE = 0, endE = 0, startM = 0, endM = 0, startC = 0, endC = 0;

    public MainForm() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboData = new javax.swing.JComboBox<>();
        comboCluster = new javax.swing.JComboBox<>();
        buttonData = new javax.swing.JButton();
        buttonRandom = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboIterasi = new javax.swing.JComboBox<>();
        buttonProses = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRandom = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        anggotaM = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        anggotaC = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        anggotaE = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        waktuC = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        waktuM = new javax.swing.JTextField();
        waktuE = new javax.swing.JTextField();
        dbiC = new javax.swing.JTextField();
        dbiM = new javax.swing.JTextField();
        dbiE = new javax.swing.JTextField();
        comboLajuAwal = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Program Clustering Data Menggunakan Algoritma Self Organizing Map");

        jLabel1.setText("Data :");

        jLabel3.setText("Jumlah Cluster :");

        comboData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Iris", "Wine", "Car Evaluation", "Abalone" }));

        comboCluster.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));

        buttonData.setText("Set");
        buttonData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDataActionPerformed(evt);
            }
        });

        buttonRandom.setText("Random");
        buttonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRandomActionPerformed(evt);
            }
        });

        jLabel4.setText("Jumlah Iterasi  : ");

        jLabel5.setText("Laju Awal :");

        comboIterasi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboIterasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "200", "300", "400", "500" }));
        comboIterasi.setPreferredSize(new java.awt.Dimension(64, 30));

        buttonProses.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonProses.setText("Proses");
        buttonProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProsesActionPerformed(evt);
            }
        });

        buttonRefresh.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Nilai DBI :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Waktu Komputasi :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Jumlah Anggota :");

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableData);

        tableRandom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableRandom);

        anggotaM.setEditable(false);
        anggotaM.setColumns(20);
        anggotaM.setRows(5);
        jScrollPane3.setViewportView(anggotaM);

        anggotaC.setEditable(false);
        anggotaC.setColumns(20);
        anggotaC.setRows(5);
        jScrollPane8.setViewportView(anggotaC);

        anggotaE.setEditable(false);
        anggotaE.setColumns(20);
        anggotaE.setRows(5);
        jScrollPane9.setViewportView(anggotaE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Euclidean");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Manhattan");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Chebyshev");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Euclidean");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Manhattan");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Chebyshev");

        waktuC.setEditable(false);
        waktuC.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Euclidean");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Manhattan");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Chebyshev");

        waktuM.setEditable(false);
        waktuM.setBackground(new java.awt.Color(255, 255, 255));

        waktuE.setEditable(false);
        waktuE.setBackground(new java.awt.Color(255, 255, 255));

        dbiC.setEditable(false);
        dbiC.setBackground(new java.awt.Color(255, 255, 255));

        dbiM.setEditable(false);
        dbiM.setBackground(new java.awt.Color(255, 255, 255));

        dbiE.setEditable(false);
        dbiE.setBackground(new java.awt.Color(255, 255, 255));

        comboLajuAwal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboLajuAwal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.4", "0.6", "0.7", "0.9" }));
        comboLajuAwal.setPreferredSize(new java.awt.Dimension(64, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(waktuE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel13)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(waktuM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboData, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboCluster, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(buttonRandom, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(buttonData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dbiE, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dbiM, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dbiC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel17)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(waktuC, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(102, 102, 102)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addGap(38, 38, 38)
                                                .addComponent(jLabel15))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(51, 51, 51)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabel11)
                                                        .addGap(36, 36, 36)
                                                        .addComponent(jLabel12))))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comboIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboLajuAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(buttonRefresh)
                                .addGap(72, 72, 72)
                                .addComponent(buttonProses, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonData))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboCluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonRandom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(comboLajuAwal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonRefresh)
                            .addComponent(buttonProses))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dbiC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbiM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dbiE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waktuC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waktuM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waktuE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        this.nilai = null;
        this.nilai2 = null;
        this.nilai3 = null;
        this.nilai4 = null;
        this.nilairandom = null;
        this.startE = 0;
        this.endE = 0;
        this.startM = 0;
        this.endM = 0;
        this.startC = 0;
        this.endC = 0;
        comboData.setSelectedIndex(0);
        comboCluster.setSelectedIndex(0);
        comboIterasi.setSelectedIndex(0);
        comboLajuAwal.setSelectedIndex(0);
        buttonData.setEnabled(true);
        buttonRandom.setEnabled(true);
        tableData.setModel(new DefaultTableModel());
        tableRandom.setModel(new DefaultTableModel());
        anggotaE.setText("");
        anggotaM.setText("");
        anggotaC.setText("");
        waktuE.setText("");
        waktuM.setText("");
        waktuC.setText("");
        dbiE.setText("");
        dbiM.setText("");
        dbiC.setText("");
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProsesActionPerformed
        if(nilairandom == null) {
            JOptionPane.showMessageDialog(null, "Data Set atau Bobot Acak Kosong", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
        else {            
            int i, j;
            int bBobot = nilairandom.length;
            int kBobot = nilairandom[0].length;
            int bData = nilai4.length;
            
            int jlhIterasi = comboIterasi.getSelectedIndex();
            int lajuawal = comboLajuAwal.getSelectedIndex();
                        
            OlahData oldok = new OlahData();
            double alpha = oldok.readLajuAwal(lajuawal);
            int iterasi = oldok.readJumlahIterasi(jlhIterasi);
            
            System.out.println("Jumlah Iterasi = "+iterasi);
                        
            
            double bobot_randomE[][] = new double[bBobot][kBobot];
            double dbiE = 0;
            
            double bobot_randomM[][] = new double[bBobot][kBobot]; 
            double dbiM = 0;
            
            
            double bobot_randomC[][] = new double[bBobot][kBobot];
            double dbiC = 0;
            
            for (i = 0; i < bBobot; i++) {
                for (j = 0; j < kBobot; j++) {
                    bobot_randomE[i][j] = nilairandom[i][j];
                    bobot_randomM[i][j] = nilairandom[i][j];
                    bobot_randomC[i][j] = nilairandom[i][j];
                }
            }
            
            Cetak ctk = new Cetak();
            System.out.println("\n====Sebelum Proses====\n");
            System.out.println("Bobot random Euclidean : ");
            ctk.cetak_double(bobot_randomE);
            System.out.println("\nBobot random Manhattan : ");
            ctk.cetak_double(bobot_randomM);
            System.out.println("\nBobot random Chebyshev : ");
            ctk.cetak_double(bobot_randomC);
            
            SOM som = new SOM();
            
            double clusterEuclidean[][] = som.testEuclidean(nilai4, bobot_randomE, alpha, iterasi);

            int[][] jlhClusterE = new int[clusterEuclidean.length][2];
          
            double clusterManhattan[][] = som.testManhattan(nilai4, bobot_randomM, alpha, iterasi);
  
            int[][] jlhClusterM = new int[clusterManhattan.length][2];
      
            double clusterChebyshev[][] = som.testChebyshev(nilai4, bobot_randomC, alpha, iterasi);
    
            int[][] jlhClusterC = new int[clusterChebyshev.length][2];
            
            System.out.println("\n\n====Setelah Proses====\n");
            System.out.println("\nSebelum Proses\n");
            System.out.println("Bobot random Euclidean : ");
            ctk.cetak_double(bobot_randomE);
            System.out.println("\nBobot random Manhattan : ");
            ctk.cetak_double(bobot_randomM);
            System.out.println("\nBobot random Chebyshev : ");
            ctk.cetak_double(bobot_randomC);         
            
           
//            System.out.println("For Euclidean ");
//            ctk.cetak_double(clusterEuclidean);
//            ctk.cetak_double(jlhClusterE);
            DBI idb = new DBI();
//            
            jlhClusterE = idb.amount2(clusterEuclidean, comboCluster.getSelectedItem().toString());
            jlhClusterM = idb.amount2(clusterManhattan, comboCluster.getSelectedItem().toString());
            jlhClusterC = idb.amount2(clusterChebyshev, comboCluster.getSelectedItem().toString());
//            jlhClusterE = idb.amount(clusterEuclidean);
//            jlhClusterM = idb.amount(clusterManhattan);
//            jlhClusterC = idb.amount(clusterChebyshev);            
////            
//            dbiE = idb.value(clusterEuclidean);
//            dbiM = idb.value(clusterManhattan);
//            dbiC = idb.value(clusterChebyshev);         
//            
//            waktuE.setText((endE - startE) + " ns");            
//            waktuM.setText((endM - startM) + " ns");
//            waktuC.setText((endC - startC) + " ns");
            
//            DecimalUtils du = new DecimalUtils();
//            dbiEuclidean.setText(""+du.round(dbiE, 3));
//            dbiManhattan.setText(""+du.round(dbiM, 3));
//            dbiChebyshev.setText(""+du.round(dbiC, 3));
            
            anggotaE.setText("Data       Cluster\n");
            for(i=0; i<bData; i++) {
                anggotaE.append(" " + i + "           " + (int) clusterEuclidean[i][0] + "\n");
            }
            anggotaE.append("\n");
            for(i=0; i<jlhClusterE.length; i++){
                anggotaE.append("Cluster "+jlhClusterE[i][0]+" : "+jlhClusterE[i][1]+"\n");
            }
            
            anggotaM.setText("Data       Cluster\n");
            for(i=0; i<bData; i++) {
                anggotaM.append(" " + i + "           " + (int) clusterManhattan[i][0] + "\n");
            }
            anggotaM.append("\n");
            for(i=0; i<jlhClusterM.length; i++){
                anggotaM.append("Cluster "+jlhClusterM[i][0]+" : "+jlhClusterM[i][1]+"\n");
            }
            
            anggotaC.setText("Data       Cluster\n");
            for(i=0; i<bData; i++) {
                anggotaC.append(" " + i + "           " + (int) clusterChebyshev[i][0] + "\n");
            }
            anggotaC.append("\n");
            for(i=0; i<jlhClusterC.length; i++){
                anggotaC.append("Cluster "+jlhClusterC[i][0]+" : "+jlhClusterC[i][1]+"\n");
            }
            
//            this.startE = 0;
//            this.endE = 0;
//            this.startM = 0;
//            this.endM = 0;
//            this.startC = 0;
//            this.endC = 0;
        }

    }//GEN-LAST:event_buttonProsesActionPerformed

    private void buttonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRandomActionPerformed

        if (nilai4 == null) {
            JOptionPane.showMessageDialog(null, "Data Set Kosong", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            nilairandom = null;
            tableRandom.setModel(new DefaultTableModel());
            int kodeCluster = comboCluster.getSelectedIndex();
            OlahData oldok = new OlahData();
            int jlhCluster = oldok.readJumlahCluster(kodeCluster);
            Matrix m = new Matrix();
            nilairandom = m.randomValue(jlhCluster, nilai);
            loadDataRandom(nilairandom);
        }

    }//GEN-LAST:event_buttonRandomActionPerformed


    private void buttonDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDataActionPerformed
        nilai = null;
        nilai2 = null;
        nilai3 = null;
        nilai4 = null;
        
        String data;
        
        data = comboData.getSelectedItem().toString();
        System.out.println("Data set adalah = "+data);
        tableData.setModel(new DefaultTableModel());
        Praproses praproses = new Praproses();
        nilai = praproses.dataValue(data);
        nilai2 = praproses.pembobotan(nilai);
        nilai3 = praproses.pengecekanMissingValue(nilai2);
        nilai4 = praproses.normalisasi(nilai3);
        loadDataMatrix(nilai4);
        buttonData.setEnabled(false);
    }//GEN-LAST:event_buttonDataActionPerformed

    private void loadDataMatrix(double data[][]) {

        int baris = data.length;
        int kolom = data[0].length;
        modelData = (DefaultTableModel) tableData.getModel();
        modelData.setColumnCount(kolom);

        for (int i = 0; i < baris; i++) {
            String row[] = new String[kolom];
            for (int j = 0; j < kolom; j++) {
                row[j] = String.valueOf(data[i][j]);
            }
            modelData.addRow(row);
        }
    }

    private void loadDataRandom(double data[][]) {

        int baris = data.length;
        int kolom = data[0].length;
        modelRandom = (DefaultTableModel) tableRandom.getModel();
        modelRandom.setColumnCount(kolom);

        for (int i = 0; i < baris; i++) {
            String row[] = new String[kolom];
            for (int j = 0; j < kolom; j++) {
                row[j] = String.valueOf(data[i][j]);
            }
            modelRandom.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea anggotaC;
    private javax.swing.JTextArea anggotaE;
    private javax.swing.JTextArea anggotaM;
    private javax.swing.JButton buttonData;
    private javax.swing.JButton buttonProses;
    private javax.swing.JButton buttonRandom;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JComboBox<String> comboCluster;
    private javax.swing.JComboBox<String> comboData;
    private javax.swing.JComboBox<String> comboIterasi;
    private javax.swing.JComboBox<String> comboLajuAwal;
    private javax.swing.JTextField dbiC;
    private javax.swing.JTextField dbiE;
    private javax.swing.JTextField dbiM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tableData;
    private javax.swing.JTable tableRandom;
    private javax.swing.JTextField waktuC;
    private javax.swing.JTextField waktuE;
    private javax.swing.JTextField waktuM;
    // End of variables declaration//GEN-END:variables
}
